name = "GreenCraft"
author = "GreenOnTheWay"
version = "26.3-2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "973479acf7dbb61158906e18063bbb778ac4d08f15ee640dce1ae76fcfb1bba2"

[versions]
minecraft = "26.3"
fabric = "0.19.5"
