name = "GreenCraft"
author = "GreenOnTheWay"
version = "26.3-2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e73a331cc1a96d4f5036cb9b750ecf38b82513556a2f9377dfdedf177d52ef29"

[versions]
minecraft = "26.3"
fabric = "0.19.5"
